package fr.formation.inti.entity;
// Generated 18 fEvr. 2022 � 08:19:10 by Hibernate Tools 3.6.0.Final


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * �quipes generated by hbm2java
 */
@Entity
@Table(name="Équipes"
    ,catalog="football"
)
public class Equipes  implements java.io.Serializable {


     private Integer idEquipes;
     private Stades stades;
     private Ligues ligues;
     private String nom;
     private byte[] logo;
     private Integer points;
     private Integer butsMarque;
     private Integer butsEncaisse;
     private Set<Matchs> matchsesForEquipesExtErieursIdEquipes = new HashSet<Matchs>(0);
     private Set<Joueurs> joueurses = new HashSet<Joueurs>(0);
     private Set<Matchs> matchsesForEquipesDomicilesIdEquipes = new HashSet<Matchs>(0);

    public Equipes() {
    }

	
    public Equipes(Stades stades, Ligues ligues) {
        this.stades = stades;
        this.ligues = ligues;
    }
    public Equipes(Stades stades, Ligues ligues, String nom, byte[] logo, Integer points, Integer butsMarque, Integer butsEncaisse, Set<Matchs> matchsesForEquipesExtErieursIdEquipes, Set<Joueurs> joueurses, Set<Matchs> matchsesForEquipesDomicilesIdEquipes) {
       this.stades = stades;
       this.ligues = ligues;
       this.nom = nom;
       this.logo = logo;
       this.points = points;
       this.butsMarque = butsMarque;
       this.butsEncaisse = butsEncaisse;
       this.matchsesForEquipesExtErieursIdEquipes = matchsesForEquipesExtErieursIdEquipes;
       this.joueurses = joueurses;
       this.matchsesForEquipesDomicilesIdEquipes = matchsesForEquipesDomicilesIdEquipes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idÉquipes", unique=true, nullable=false)
    public Integer getIdEquipes() {
        return this.idEquipes;
    }
    
    public void setIdEquipes(Integer idEquipes) {
        this.idEquipes = idEquipes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="stades_idstades", nullable=false)
    public Stades getStades() {
        return this.stades;
    }
    
    public void setStades(Stades stades) {
        this.stades = stades;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ligues_idligues", nullable=false)
    public Ligues getLigues() {
        return this.ligues;
    }
    
    public void setLigues(Ligues ligues) {
        this.ligues = ligues;
    }

    
    @Column(name="nom", length=45)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="logo")
    public byte[] getLogo() {
        return this.logo;
    }
    
    public void setLogo(byte[] logo) {
        this.logo = logo;
    }

    
    @Column(name="points")
    public Integer getPoints() {
        return this.points;
    }
    
    public void setPoints(Integer points) {
        this.points = points;
    }

    
    @Column(name="buts marqué")
    public Integer getButsMarque() {
        return this.butsMarque;
    }
    
    public void setButsMarque(Integer butsMarque) {
        this.butsMarque = butsMarque;
    }

    
    @Column(name="buts encaissé")
    public Integer butsEncaisse() {
        return this.butsEncaisse;
    }
    
    public void setButsEncaisse(Integer butsEncaisse) {
        this.butsEncaisse = butsEncaisse;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="equipesByEquipesExtErieursIdEquipes")
    public Set<Matchs> getMatchsesForEquipesExtErieursIdEquipes() {
        return this.matchsesForEquipesExtErieursIdEquipes;
    }
    
    public void setMatchsesForEquipesExtErieursIdEquipes(Set<Matchs> matchsesForEquipesExtErieursIdEquipes) {
        this.matchsesForEquipesExtErieursIdEquipes = matchsesForEquipesExtErieursIdEquipes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="Equipes")
    public Set<Joueurs> getJoueurses() {
        return this.joueurses;
    }
    
    public void setJoueurses(Set<Joueurs> joueurses) {
        this.joueurses = joueurses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="equipesByEquipesDomicilesIdEquipes")
    public Set<Matchs> getMatchsesForEquipesDomicilesIdEquipes() {
        return this.matchsesForEquipesDomicilesIdEquipes;
    }
    
    public void setMatchsesForEquipesDomicilesIdEquipes(Set<Matchs> matchsesForEquipesDomicilesIdEquipes) {
        this.matchsesForEquipesDomicilesIdEquipes = matchsesForEquipesDomicilesIdEquipes;
    }




}
