package fr.formation.inti.entity;
// Generated 18 f�vr. 2022 � 08:19:10 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Joueurs generated by hbm2java
 */
@Entity
@Table(name = "joueurs", catalog = "football")
public class Joueurs implements java.io.Serializable {

	private int idjoueurs;
	private Equipes Equipes;
	private String noms;
	private Integer stats;
	private String postes;

	public Joueurs() {
	}

	public Joueurs(int idjoueurs, Equipes Equipes) {
        this.idjoueurs = idjoueurs;
        this.Equipes = Equipes;
    }

	public Joueurs(int idjoueurs, Equipes Equipes, String noms, Integer stats, String postes) {
       this.idjoueurs = idjoueurs;
       this.Equipes = Equipes;
       this.noms = noms;
       this.stats = stats;
       this.postes = postes;
    }

	@Id

	@Column(name = "idjoueurs", unique = true, nullable = false)
	public int getIdjoueurs() {
		return this.idjoueurs;
	}

	public void setIdjoueurs(int idjoueurs) {
		this.idjoueurs = idjoueurs;
	}

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Equipes_idEquipes", nullable=false)
    public Equipes getEquipes() {
        return this.Equipes;
    }

	public void setEquipes(Equipes Equipes) {
        this.Equipes = Equipes;
    }

	@Column(name = "noms", length = 45)
	public String getNoms() {
		return this.noms;
	}

	public void setNoms(String noms) {
		this.noms = noms;
	}

	@Column(name = "stats")
	public Integer getStats() {
		return this.stats;
	}

	public void setStats(Integer stats) {
		this.stats = stats;
	}

	@Column(name = "postes", length = 45)
	public String getPostes() {
		return this.postes;
	}

	public void setPostes(String postes) {
		this.postes = postes;
	}

}
