package fr.formation.inti.entity;
// Generated 18 fEvr. 2022 E 08:19:10 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Ligues generated by hbm2java
 */
@Entity
@Table(name = "ligues", catalog = "football")
public class Ligues implements java.io.Serializable {

	private int idligues;
	private String nom;
	private byte[] logo;

	private Set<Equipes> equipes = new HashSet<Equipes>(0);

    public Ligues() {
    }

	public Ligues(int idligues) {
		this.idligues = idligues;
	}

	public Ligues(int idligues, String nom, byte[] logo, Set<Equipes> equipes) {
       this.idligues = idligues;
       this.nom = nom;
       this.logo = logo;
       this.equipes = equipes;
    }

	@Id

	@Column(name = "idligues", unique = true, nullable = false)
	public int getIdligues() {
		return this.idligues;
	}

	public void setIdligues(int idligues) {
		this.idligues = idligues;
	}

	@Column(name = "nom", length = 45)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "logo")
	public byte[] getLogo() {
		return this.logo;
	}

	public void setLogo(byte[] logo) {
		this.logo = logo;
	}

@OneToMany(fetch=FetchType.LAZY, mappedBy="ligues")
    public Set<Equipes> getEquipes() {
        return this.equipes;
    }

	public void setEquipes(Set<Equipes> equipes) {
        this.equipes = equipes;
    }




}
