package fr.formation.inti.entity;
// Generated 18 févr. 2022 é 08:19:10 by Hibernate Tools 3.6.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MatchsId generated by hbm2java
 */
@Embeddable
public class MatchsId implements java.io.Serializable {

	private int idMatch;

	private int équipesExtérieursIdéquipes;
     private int équipesDomicilesIdéquipes;

    public MatchsId() {
    }

	public MatchsId(int idMatch, int équipesExtérieursIdéquipes, int équipesDomicilesIdéquipes) {
       this.idMatch = idMatch;
       this.équipesExtérieursIdéquipes = équipesExtérieursIdéquipes;
       this.équipesDomicilesIdéquipes = équipesDomicilesIdéquipes;
    }

	@Column(name = "idMatch", nullable = false)
	public int getIdMatch() {
		return this.idMatch;
	}

	public void setIdMatch(int idMatch) {
		this.idMatch = idMatch;
	}

	@Column(name="équipes_extérieurs_idéquipes", nullable=false)
    public int getéquipesExtérieursIdéquipes() {
        return this.équipesExtérieursIdéquipes;
    }

	public void setéquipesExtérieursIdéquipes(int équipesExtérieursIdéquipes) {
        this.équipesExtérieursIdéquipes = équipesExtérieursIdéquipes;
    }

	@Column(name="équipes_domiciles_idéquipes", nullable=false)
    public int getéquipesDomicilesIdéquipes() {
        return this.équipesDomicilesIdéquipes;
    }

	public void setéquipesDomicilesIdéquipes(int équipesDomicilesIdéquipes) {
        this.équipesDomicilesIdéquipes = équipesDomicilesIdéquipes;
    }

	public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MatchsId) ) return false;
		 MatchsId castOther = ( MatchsId ) other; 
         
		 return (this.getIdMatch()==castOther.getIdMatch())
 && (this.getéquipesExtérieursIdéquipes()==castOther.getéquipesExtérieursIdéquipes())
 && (this.getéquipesDomicilesIdéquipes()==castOther.getéquipesDomicilesIdéquipes());
   }

	public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdMatch();
         result = 37 * result + this.getéquipesExtérieursIdéquipes();
         result = 37 * result + this.getéquipesDomicilesIdéquipes();
         return result;
   }

}
