package fr.formation.inti.entity;
// Generated 18 févr. 2022 é 08:19:10 by Hibernate Tools 3.6.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Matchs generated by hbm2java
 */
@Entity
@Table(name = "matchs", catalog = "football")
public class Matchs implements java.io.Serializable {

	private MatchsId id;
	private Stades stades;
	private Equipes equipesByEquipesDomicilesIdEquipes;
	private Equipes equipesByEquipesExterieursIdEquipes;
	private String dates;
	private String scores;
	private String horaires;
	private Integer journee;

	public Matchs() {
	}

	public Matchs(MatchsId id, Stades stades, Equipes equipesByEquipesDomicilesIdEquipes, Equipes equipesByEquipesExterieursIdEquipes) {
        this.id = id;
        this.stades = stades;
        this.equipesByEquipesDomicilesIdEquipes = equipesByEquipesDomicilesIdEquipes;
        this.equipesByEquipesExterieursIdEquipes = equipesByEquipesExterieursIdEquipes;
    }

	public Matchs(MatchsId id, Stades stades, Equipes equipesByEquipesDomicilesIdEquipes, Equipes equipesByEquipesExterieursIdEquipes, String dates, String scores, String horaires, Integer journee) {
       this.id = id;
       this.stades = stades;
       this.equipesByEquipesDomicilesIdEquipes = equipesByEquipesDomicilesIdEquipes;
       this.equipesByEquipesExterieursIdEquipes = equipesByEquipesExterieursIdEquipes;
       this.dates = dates;
       this.scores = scores;
       this.horaires = horaires;
       this.journee = journee;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idMatch", column=@Column(name="idMatch", nullable=false) ), 
        @AttributeOverride(name="equipeByEquipeExterieursIdEquipe", column=@Column(name="Équipes_extérieurs_idÉquipes", nullable=false) ), 
        @AttributeOverride(name="equipeByEquipeDomicilesIdEquipe", column=@Column(name="Équipes_domiciles_idÉquipes", nullable=false) ) } )
    public MatchsId getId() {
        return this.id;
    }

	public void setId(MatchsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stades_idstades", nullable = false)
	public Stades getStades() {
		return this.stades;
	}

	public void setStades(Stades stades) {
		this.stades = stades;
	}

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Équipes_domiciles_idÉquipes", nullable=false, insertable=false, updatable=false)
    public Equipes getEquipesByEquipesDomicilesIdEquipes() {
        return this.equipesByEquipesDomicilesIdEquipes;
    }

	public void setEquipesByEquipesDomicilesIdEquipes(Equipes equipesByEquipesDomicilesIdEquipes) {
        this.equipesByEquipesDomicilesIdEquipes = equipesByEquipesDomicilesIdEquipes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Equipe_extérieurs_idEquipe", nullable=false, insertable=false, updatable=false)
    public Equipes getEquipeByEquipeExterieursIdEquipe() {
        return this.equipesByEquipesExterieursIdEquipes;
    }

	public void setEquipeByEquipeExterieursIdEquipe(Equipes equipesByEquipesExterieursIdEquipes) {
        this.equipesByEquipesExterieursIdEquipes = equipesByEquipesExterieursIdEquipes;
    }

	@Column(name = "Dates", length = 45)
	public String getDates() {
		return this.dates;
	}

	public void setDates(String dates) {
		this.dates = dates;
	}

	@Column(name = "Scores", length = 45)
	public String getScores() {
		return this.scores;
	}

	public void setScores(String scores) {
		this.scores = scores;
	}

	@Column(name = "horaires", length = 45)
	public String getHoraires() {
		return this.horaires;
	}

	public void setHoraires(String horaires) {
		this.horaires = horaires;
	}

	@Column(name="journée")
    public Integer getJournee() {
        return this.journee;
    }

	public void setJournee(Integer journee) {
        this.journee = journee;
    }




}
