package fr.formation.inti.entity;
// Generated 18 févr. 2022 é 08:19:10 by Hibernate Tools 3.6.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Matchs generated by hbm2java
 */
@Entity
@Table(name = "matchs", catalog = "football")
public class Matchs implements java.io.Serializable {

	private MatchsId id;
	private Stades stades;
	private Équipes équipesByéquipesDomicilesIdéquipes;
	private Équipes équipesByéquipesExtérieursIdéquipes;
	private String dates;
	private String scores;
	private String horaires;
	private Integer journée;

	public Matchs() {
	}

	public Matchs(MatchsId id, Stades stades, Équipes équipesByéquipesDomicilesIdéquipes, équipes équipesByéquipesExtérieursIdéquipes) {
        this.id = id;
        this.stades = stades;
        this.équipesByéquipesDomicilesIdéquipes = équipesByéquipesDomicilesIdéquipes;
        this.équipesByéquipesExtérieursIdéquipes = équipesByéquipesExtérieursIdéquipes;
    }

	public Matchs(MatchsId id, Stades stades, Équipes équipesByéquipesDomicilesIdéquipes, équipes équipesByéquipesExtérieursIdéquipes, String dates, String scores, String horaires, Integer journée) {
       this.id = id;
       this.stades = stades;
       this.équipesByéquipesDomicilesIdéquipes = équipesByéquipesDomicilesIdéquipes;
       this.équipesByéquipesExtérieursIdéquipes = équipesByéquipesExtérieursIdéquipes;
       this.dates = dates;
       this.scores = scores;
       this.horaires = horaires;
       this.journée = journée;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idMatch", column=@Column(name="idMatch", nullable=false) ), 
        @AttributeOverride(name="équipesExtérieursIdéquipes", column=@Column(name="équipes_extérieurs_idéquipes", nullable=false) ), 
        @AttributeOverride(name="équipesDomicilesIdéquipes", column=@Column(name="équipes_domiciles_idéquipes", nullable=false) ) } )
    public MatchsId getId() {
        return this.id;
    }

	public void setId(MatchsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "stades_idstades", nullable = false)
	public Stades getStades() {
		return this.stades;
	}

	public void setStades(Stades stades) {
		this.stades = stades;
	}

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="équipes_domiciles_idéquipes", nullable=false, insertable=false, updatable=false)
    public Équipes getéquipesByéquipesDomicilesIdéquipes() {
        return this.équipesByéquipesDomicilesIdéquipes;
    }

	public void setéquipesByéquipesDomicilesIdéquipes(Équipes équipesByéquipesDomicilesIdéquipes) {
        this.équipesByéquipesDomicilesIdéquipes = équipesByéquipesDomicilesIdéquipes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="équipes_extérieurs_idéquipes", nullable=false, insertable=false, updatable=false)
    public Équipes getéquipesByéquipesExtérieursIdéquipes() {
        return this.équipesByéquipesExtérieursIdéquipes;
    }

	public void setéquipesByéquipesExtérieursIdéquipes(Équipes équipesByéquipesExtérieursIdéquipes) {
        this.équipesByéquipesExtérieursIdéquipes = équipesByéquipesExtérieursIdéquipes;
    }

	@Column(name = "Dates", length = 45)
	public String getDates() {
		return this.dates;
	}

	public void setDates(String dates) {
		this.dates = dates;
	}

	@Column(name = "Scores", length = 45)
	public String getScores() {
		return this.scores;
	}

	public void setScores(String scores) {
		this.scores = scores;
	}

	@Column(name = "horaires", length = 45)
	public String getHoraires() {
		return this.horaires;
	}

	public void setHoraires(String horaires) {
		this.horaires = horaires;
	}

	@Column(name="journée")
    public Integer getJournée() {
        return this.journée;
    }

	public void setJournée(Integer journée) {
        this.journée = journée;
    }




}
