package fr.formation.inti.entity;
// Generated 18 févr. 2022 é 08:19:10 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "football")
public class Role implements java.io.Serializable {

	private int idRole;
	private String nomRole;
	private Set<User> users = new HashSet<User>(0);

	public Role() {
	}

	public Role(int idRole) {
		this.idRole = idRole;
	}

	public Role(int idRole, String nomRole, Set<User> users) {
		this.idRole = idRole;
		this.nomRole = nomRole;
		this.users = users;
	}

	@Id

	@Column(name = "idRole", unique = true, nullable = false)
	public int getIdRole() {
		return this.idRole;
	}

	public void setIdRole(int idRole) {
		this.idRole = idRole;
	}

	@Column(name = "nomRole", length = 45)
	public String getNomRole() {
		return this.nomRole;
	}

	public void setNomRole(String nomRole) {
		this.nomRole = nomRole;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role")
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

}
