package fr.formation.inti.entity;
// Generated 18 févr. 2022 é 08:19:10 by Hibernate Tools 3.6.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Stades generated by hbm2java
 */
@Entity
@Table(name = "stades", catalog = "football")
public class Stades implements java.io.Serializable {

	private int idstades;
	private String names;
	private Integer capacité;
	private Integer surface;
	private String villes;
	private Set<Équipes>équipeses=new HashSet<Équipes>(0);
	private Set<Matchs> matchses = new HashSet<Matchs>(0);

	public Stades() {
	}

	public Stades(int idstades) {
		this.idstades = idstades;
	}

	public Stades(int idstades, String names, Integer capacité, Integer surface, String villes, Set<équipes> équipeses, Set<Matchs> matchses) {
       this.idstades = idstades;
       this.names = names;
       this.capacité = capacité;
       this.surface = surface;
       this.villes = villes;
       this.équipeses = équipeses;
       this.matchses = matchses;
    }

	@Id

	@Column(name = "idstades", unique = true, nullable = false)
	public int getIdstades() {
		return this.idstades;
	}

	public void setIdstades(int idstades) {
		this.idstades = idstades;
	}

	@Column(name = "names", length = 45)
	public String getNames() {
		return this.names;
	}

	public void setNames(String names) {
		this.names = names;
	}

	@Column(name="capacité")
    public Integer getCapacité()
	{
        return this.capacité;
    }

	public void setCapacité(Integer capacité)
	{
        this.capacité = capacité;
    }

	@Column(name = "surface")
	public Integer getSurface() {
		return this.surface;
	}

	public void setSurface(Integer surface) {
		this.surface = surface;
	}

	@Column(name = "Villes", length = 45)
	public String getVilles() {
		return this.villes;
	}

	public void setVilles(String villes) {
		this.villes = villes;
	}

@OneToMany(fetch=FetchType.LAZY, mappedBy="stades")
    public Set<Équipes> getéquipeses() {
        return this.équipeses;
    }

	public void setéquipeses(Set<Équipes> équipeses) {
        this.équipeses = équipeses;
    }

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "stades")
	public Set<Matchs> getMatchses() {
		return this.matchses;
	}

	public void setMatchses(Set<Matchs> matchses) {
		this.matchses = matchses;
	}

}
